{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Update Extensions' %}{% endblock %}

{% set active_menu = 'updateExt' %}

{% block content %}

<div class="widget first">
    <div class="head">
        <h5>{% trans 'Update Extensions' %}</h5>
    </div>

    <div class="help">
        <h3>{% trans 'Moduł do aktualizacji modułów BoxBilling.pl' %}</h3>
    </div>

     <table class="tableStatic wide">
        <tbody>

		{% for jss in json %}
			<tr>
                <td>{{jss['name']}}<br />
                <strong>Wersja na GitHub:</strong>{{ jss['git_version'] }}<br />
				<strong>Wersja na serwerze:</strong> {{ jss['aktualna_wersja'] }}<br />
				</td>
				<td align="right">

					<form method="post" action="admin/updateExt/install" class="mainForm api-form" data-api-msg="{% trans 'install' %}">
					<input type="hidden" name="filename" value="{{jss['namefull']}}" />
					<input type="hidden" name="url" value="{{jss['svn_url']}}" />
					<button type="submit" class="greyishBtn">{% trans 'Upload' %}</button>
					</form>
				</td>
				</tr>
		{% endfor %}
		

        </tbody>
    </table>
    
</div>

{% endblock %}